# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Personal info
name: GongKangYi
title: Xidian University
email: gongkangyi@foxmail.com
#phone: Your phone number (optional)
#website: gongkangyi.github.io/blog

# Social links
twitter_username: jekyllrb
github_username:  gongkangyi
facebook_username: jekyll

# About Section
about_title: Biography
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am GongKangYi. I am pursuing my master's degree in Electronic and Communication Engineering at Xidian University. 
  I received the B.S. degrees from Electronics & Information School, Yangtze University, Jingzhou, China, in 2017. 
  During my college life, I have won a national scholarship honor. 

  At the stage of postgraduate, my research interests fall under the umbrella of Internet of Things (IoT), 
  particularly Smart Cities, Fog Computing, Edge computing, and also Computer vision application such as Motion Detection and Facial recognition.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Skills #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  **Languages:** Java, Shell, Python, C/C++

  **Technologies:** Linux, Spring, MySQL, Redis


# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
